import type { Metadata } from "next";
import { Kaisei_Opti, Hina_Mincho } from "next/font/google";
import "./globals.css";

const kaisei = Kaisei_Opti({
  variable: "--font-kaisei",
  weight: "400",
  subsets: ["latin"],
});

const hina = Hina_Mincho({
  variable: "--font-hina",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${kaisei.variable} ${hina.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
